# permissions for end users to edit vscodeonlines.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: vscodeonline-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: web-ide
    app.kubernetes.io/part-of: web-ide
    app.kubernetes.io/managed-by: kustomize
  name: vscodeonline-editor-role
rules:
- apiGroups:
  - vscode.daocloud.io
  resources:
  - vscodeonlines
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - vscode.daocloud.io
  resources:
  - vscodeonlines/status
  verbs:
  - get
